server:
  port: 8080 # ??????

spring:
  application:
    name: ecommerce-platform

  # 1. ??????? (???????)
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. JPA ???????
  jpa:
    hibernate:
      ddl-auto: update # ??????? (???????????)
    show-sql: true     # ?????? SQL????????????
    properties:
      hibernate:
        format_sql: true # ??? SQL???????

  # 3. ???? (??????)
  security:
    user:
      name: user
      password: 123456 # ????? user / 123456 ??